name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins job
        run: |
          curl -X POST "http://127.0.0.1:8080/job/workshop2/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
